import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { normalizeWebsite, saveBrandConfig } from '../lib/brand-config'
import type { TrackingMode } from '../lib/brand-config'

export default function OnboardingPage() {
  const navigate = useNavigate(); const [step, setStep] = useState(1); const [brandName, setBrandName] = useState(''); const [website, setWebsite] = useState(''); const [trackingMode, setTrackingMode] = useState<TrackingMode>('website'); const [promptText, setPromptText] = useState(''); const [error, setError] = useState('')
  function next() { const normalized = normalizeWebsite(website); if (!brandName.trim()) { setError('Brand name is required.'); return } if (!normalized) { setError('Enter a valid website, such as geosuite.ai.'); return } setWebsite(normalized); setError(''); setStep(2) }
  function finish() { const prompts = promptText.split('\n').map(p => p.trim()).filter(Boolean); if (!saveBrandConfig({ brandName: brandName.trim(), website, trackingMode, prompts })) { setError('We could not save your setup. Please try again.'); return } navigate('/dashboard') }
  return <div className="onboarding-shell"><header className="topbar"><div className="auth-brand"><div className="brand-mark">G</div><span>GeoSuite</span></div><span className="step-count">Step {step} of 2</span></header><div className="progress"><span style={{ width: `${step * 50}%` }} /></div><main className="onboarding-main"><div className="eyebrow">Set up your workspace</div>{step === 1 ? <><h1>Let’s measure your brand.</h1><p className="lede">Start with the basics. We’ll use these details to find your brand in AI-generated answers.</p><div className="setup-card stack"><label>Brand name<input autoFocus value={brandName} onChange={e => { setBrandName(e.target.value); setError('') }} placeholder="e.g. GeoSuite" /></label><label>Website<input value={website} onChange={e => { setWebsite(e.target.value); setError('') }} placeholder="yourbrand.com" /><span className="field-hint">We’ll scan your public presence, not your private analytics.</span></label>{error && <p className="error-text">{error}</p>}<button className="button primary wide" onClick={next}>Continue <span>→</span></button></div></> : <><h1>What should we watch?</h1><p className="lede">Choose the signal that matters most now. You can add more tracking later.</p><div className="mode-grid"><button className={`mode-card ${trackingMode === 'website' ? 'selected' : ''}`} onClick={() => setTrackingMode('website')}><span className="mode-icon">◎</span><span><strong>Brand presence</strong><small>Find your brand across relevant AI answers.</small></span><span className="radio" /></button><button className={`mode-card ${trackingMode === 'prompts' ? 'selected' : ''}`} onClick={() => setTrackingMode('prompts')}><span className="mode-icon">⌁</span><span><strong>Topics & prompts</strong><small>Track the questions your audience asks.</small></span><span className="radio" /></button></div><label className="prompt-label">Prompts <span>Optional</span><textarea value={promptText} onChange={e => setPromptText(e.target.value)} placeholder="One prompt per line, e.g.\nWhat is the best analytics tool for…" rows={4} /></label><p className="field-hint">You can skip this and start with website discovery.</p>{error && <p className="error-text">{error}</p>}<div className="onboarding-actions"><button className="button ghost" onClick={() => setStep(1)}>Back</button><button className="button primary" onClick={finish}>Start tracking <span>→</span></button></div></>}<p className="secure-note">⌁ Your workspace is private and encrypted.</p></main></div>
}
