import { and, eq, sql } from 'drizzle-orm'
import type pg from 'pg'
import type { AccuracyFlag, Citation, EngineId, ObservationRow } from '@geosuite/shared'
import { withOrg } from '../client.js'
import { citations, dailyMetrics, observations, probeResults, probeRuns } from '../schema/index.js'
export interface ProbeRunRepository { create(orgId:string,input:{brandId:string;day:string;totalJobs:number}):Promise<string>; markJob(orgId:string,runId:string,outcome:'succeeded'|'failed'):Promise<void>; complete(orgId:string,runId:string,coverage:number):Promise<void> }
export function createProbeRunRepository(pool:pg.Pool):ProbeRunRepository{return {async create(orgId,input){return withOrg(pool,orgId,async tx=>{const [r]=await tx.insert(probeRuns).values({orgId,brandId:input.brandId,day:input.day,totalJobs:input.totalJobs,status:'running'}).returning({id:probeRuns.id});return r!.id})},async markJob(orgId,runId,outcome){await withOrg(pool,orgId,tx=>tx.update(probeRuns).set({[outcome==='succeeded'?'succeededJobs':'failedJobs']:sql`${outcome==='succeeded'?probeRuns.succeededJobs:probeRuns.failedJobs} + 1`}).where(eq(probeRuns.id,runId)).then(()=>undefined))},async complete(orgId,runId,coverage){await withOrg(pool,orgId,tx=>tx.update(probeRuns).set({status:'completed',coverage:coverage.toFixed(4),completedAt:new Date()}).where(eq(probeRuns.id,runId)).then(()=>undefined))}}}
export interface ProbeResultInput {runId:string;promptId:string;engineId:EngineId;model:string;rawText:string;latencyMs:number;cacheHit:boolean;citations:Citation[];ownDomains:string[]}
export interface ProbeResultRepository {insert(orgId:string,input:ProbeResultInput):Promise<string>}
export function hostnameOf(url:string):string {try{return new URL(url).hostname.replace(/^www\./,'').toLowerCase()}catch{return ''}}
export function isOwnDomain(url:string,domains:string[]):boolean {const host=hostnameOf(url); return host!==''&&domains.some(raw=>{const d=raw.replace(/^www\./,'').toLowerCase();return host===d||host.endsWith(`.${d}`)})}
export function createProbeResultRepository(pool:pg.Pool):ProbeResultRepository{return {async insert(orgId,input){return withOrg(pool,orgId,async tx=>{const [r]=await tx.insert(probeResults).values({orgId,runId:input.runId,promptId:input.promptId,engineId:input.engineId,model:input.model,rawText:input.rawText,latencyMs:input.latencyMs,cacheHit:input.cacheHit}).onConflictDoNothing().returning({id:probeResults.id});if(!r){const [existing]=await tx.select({id:probeResults.id}).from(probeResults).where(and(eq(probeResults.orgId,orgId),eq(probeResults.runId,input.runId),eq(probeResults.promptId,input.promptId),eq(probeResults.engineId,input.engineId)));return existing!.id}const id=r.id;if(input.citations.length)await tx.insert(citations).values(input.citations.map(c=>({orgId,probeResultId:id,url:c.url,domain:hostnameOf(c.url),title:c.title,position:c.position,isOwnDomain:isOwnDomain(c.url,input.ownDomains)})));return id})}}}
export interface ObservationInput extends ObservationRow {runId:string}
export interface ObservationRepository {insert(orgId:string,input:ObservationInput):Promise<void>;listByRun(orgId:string,runId:string):Promise<ObservationRow[]>}
export function createObservationRepository(pool:pg.Pool):ObservationRepository{return {async insert(orgId,input){await withOrg(pool,orgId,tx=>tx.insert(observations).values({orgId,runId:input.runId,promptId:input.promptId,engineId:input.engineId,mentioned:input.mentioned,position:input.position,sentiment:input.sentiment===null?null:input.sentiment.toFixed(2),citedOwnDomain:input.citedOwnDomain,competitorIds:input.competitorIds,accuracyFlags:input.accuracyFlags}).onConflictDoNothing().then(()=>undefined))},async listByRun(orgId,runId){return withOrg(pool,orgId,async tx=>(await tx.select().from(observations).where(eq(observations.runId,runId))).map(r=>({promptId:r.promptId,engineId:r.engineId as EngineId,mentioned:r.mentioned,position:r.position,sentiment:r.sentiment===null?null:Number(r.sentiment),citedOwnDomain:r.citedOwnDomain,competitorIds:r.competitorIds,accuracyFlags:r.accuracyFlags as AccuracyFlag[]})))}}}
export interface DailyMetricInput {brandId:string;day:string;visibilityRate:number;shareOfVoice:number;citationRate:number;averagePosition:number|null;sentimentScore:number|null;accuracyFlagCount:number;coverage:number}
export interface DailyMetricRepository {upsert(orgId:string,input:DailyMetricInput):Promise<void>}
export function createDailyMetricRepository(pool:pg.Pool):DailyMetricRepository{return {async upsert(orgId,input){const v={orgId,brandId:input.brandId,day:input.day,visibilityRate:input.visibilityRate.toFixed(4),shareOfVoice:input.shareOfVoice.toFixed(4),citationRate:input.citationRate.toFixed(4),averagePosition:input.averagePosition===null?null:input.averagePosition.toFixed(2),sentimentScore:input.sentimentScore===null?null:input.sentimentScore.toFixed(2),accuracyFlagCount:input.accuracyFlagCount,coverage:input.coverage.toFixed(4),updatedAt:new Date()};await withOrg(pool,orgId,tx=>tx.insert(dailyMetrics).values(v).onConflictDoUpdate({target:[dailyMetrics.orgId,dailyMetrics.brandId,dailyMetrics.day],set:v}).then(()=>undefined))}}}
