import { z } from 'zod'
import type { AccuracyFlag, BrandProfile, TokenUsage } from '@geosuite/shared'
import { tokenCost } from '@geosuite/engines'
import type { CandidateMatch } from './candidates.js'
export interface ConfirmInput { text: string; brand: BrandProfile; candidates: CandidateMatch[] }
export interface ConfirmResult { brandMentioned: boolean; brandPosition: number | null; sentiment: number | null; competitorIds: string[]; accuracyFlags: AccuracyFlag[]; usage: TokenUsage }
export interface Confirmer { confirm(input: ConfirmInput): Promise<ConfirmResult> }
export const confirmResultSchema = z.object({ brandMentioned: z.boolean(), brandPosition: z.number().int().min(1).nullable(), sentiment: z.number().min(-1).max(1).nullable(), competitorIds: z.array(z.string()), accuracyFlags: z.array(z.object({ factId: z.string(), statedIncorrectly: z.string() })) })
export function buildConfirmPrompt(input: ConfirmInput): string { return ['Identify whether the tracked brand is mentioned in this AI answer. Return only JSON.', `Brand: ${input.brand.name}`, `Aliases: ${input.brand.aliases.join(', ') || '(none)'}`, `Description: ${input.brand.entityDescription}`, `Facts: ${input.brand.facts.map((fact) => `${fact.id}: ${fact.claim}`).join('; ') || '(none)'}`, `Competitors: ${input.brand.competitors.map((competitor) => `${competitor.id}: ${competitor.name}`).join('; ') || '(none)'}`, `Candidates: ${input.candidates.map((candidate) => `${candidate.entityId}@${candidate.offset}`).join(', ')}`, `Answer:\n${input.text}`].join('\n') }
export interface LlmConfirmerConfig { apiKey: string; model: string; baseUrl?: string; inputCostPerMTok: number; outputCostPerMTok: number; fetchImpl?: typeof fetch }
export function createLlmConfirmer(config: LlmConfirmerConfig): Confirmer { const doFetch = config.fetchImpl ?? fetch; const baseUrl = config.baseUrl ?? 'https://api.openai.com/v1'; return { async confirm(input) { const response = await doFetch(`${baseUrl}/responses`, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${config.apiKey}` }, body: JSON.stringify({ model: config.model, input: buildConfirmPrompt(input), text: { format: { type: 'json_object' } } }) }); if (!response.ok) throw new Error(`Confirmation failed with ${response.status}`); const body = await response.json() as { output?: { content?: { type: string; text?: string }[] }[]; usage?: { input_tokens?: number; output_tokens?: number } }; const raw = (body.output ?? []).flatMap((item) => item.content ?? []).find((item) => item.type === 'output_text')?.text; if (!raw) throw new Error('Confirmation response does not contain output_text'); const parsed = confirmResultSchema.safeParse(JSON.parse(raw)); if (!parsed.success) throw new Error(`Confirmation response does not match schema: ${parsed.error.message}`); const competitorIds = new Set(input.brand.competitors.map((item) => item.id)); const facts = new Set(input.brand.facts.map((item) => item.id)); const inputTokens = body.usage?.input_tokens ?? 0; const outputTokens = body.usage?.output_tokens ?? 0; return { ...parsed.data, brandPosition: parsed.data.brandMentioned ? parsed.data.brandPosition : null, sentiment: parsed.data.brandMentioned ? parsed.data.sentiment : null, competitorIds: parsed.data.competitorIds.filter((id) => competitorIds.has(id)), accuracyFlags: parsed.data.accuracyFlags.filter((flag) => facts.has(flag.factId)), usage: { inputTokens, outputTokens, costUsd: tokenCost(inputTokens, outputTokens, config.inputCostPerMTok, config.outputCostPerMTok) } } } } }
